%\VignetteIndexEntry{spbtest5}
%\VignetteKeywords{spbtest5}
%\VignettePackage{spbtest5}
\documentclass{article}

\title{An Introduction to the spbtest5 Package}
\author{Lori Shepherd}
\date{\today}

\begin{document}

\maketitle

\tableofcontents

\section{Introduction}
A test package 

<<eval=TRUE>>=
# workflow and data experiment get 4800 sec (80 min)
Sys.sleep(1)
vl = c(me = "soemthing", to = "stuff")
cat("value is a ", class(vl)) 
@ 

\end{document}
